# Generated by Django 4.1.4 on 2022-12-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="upload",
            field=models.FileField(upload_to="movies", verbose_name="upload"),
        ),
    ]
