# Generated by Django 4.1.4 on 2022-12-23 18:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0003_moviewatch"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MovieWatch",
            new_name="MovieSession",
        ),
    ]
